### ISSUE TITLE
Warning for Critical dependency

### ISSUE THREAD

**Issue by guntram** [log4js/log4js#1]
We use log4js in an angular11 app, and a warning comes up when using it:

`Warning: ./node_modules/log4js/lib/appenders/index.js 26:11-30
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Users\<username>\git\<appname>\node_modules\webpack\lib\dependencies\ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\<username>\git\<appname>\node_modules\webpack\lib\Compilation.js:1454:24)
    at C:\Users\<username>\git\<appname>\node_modules\webpack\lib\Compilation.js:1258:10
    at _next0 (eval at create (C:\Users\<username>\git\<appname>\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
    at eval (eval at create (C:\Users\<username>\git\<appname>\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:45:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 @ ./node_modules/log4js/lib/log4js.js
 @ ./src/app/shared/services/logstash.service.ts
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

which comes form this line (index.js:26):

`return require(modulePath); //eslint-disable-line`

As a workaround, we can modify this line to look like:

```return require(`${modulePath}`); //eslint-disable-line```

**Comment by stritti** [comment]
Could you create a pull request to solve it here?

**Comment by guntram** [comment]
Hey, sorry, I think it was the wrong repo.
That's why I closed it already.
We are using log4js-node, which is installed only by 'log4js', and this lead to a little confusion :)

**Comment by stritti** [comment]
OK, I see. 
Log4js-node was split long time ago from this project.
